### ISSUE TITLE
Kursplanung: Druckausgabe 

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#110]
Ich hätte gerne eine Kursübersicht bei der Druckausgabe der Kursplanung. Also einfach die Tabelle der Kurse als PDF, so wie sie in der Kursplanungs-Tabelle aufgeführt sind.
Gerne inkl. der Schienen...
Aber auf jeden Fall mit: Kursbezeichnung, Lehrkraft, FW, KD, Kursgröße

<img width="760" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/186801f2-1c3b-4e09-8473-9df2cf400380">

**Comment by HHayen** [comment]
Schließe mich an: Bitte auch mit Anzahl GKS/GKM.

**Comment by M-Plu** [comment]
Im aktuellen dev ist ein Bericht enthalten (Kurse mit Statistikwerten). Einfach mal im Druckmenü der Kursplanung schauen. Berücksichtig werden alle selektierten Kurse.

**Comment by NielsWL** [comment]
Finde ich nicht...

![image](https://github.com/user-attachments/assets/bb734a5f-4b1a-4389-a0f0-ff6e5fb1a0c9)

**Comment by M-Plu** [comment]
Welche Version hat denn der Client? Auch neu gebaut?

**Comment by NielsWL** [comment]
Gestern neu gebaut

**Comment by NielsWL** [comment]
ok, jetzt taucht es auf. In der letzten Q1 geht es, das war eine restaurierte Blockung. In der kommenden EF geht es nicht.

```json
{
  "env": {
    "mode": "stable",
    "version": "0.9.1-SNAPSHOT",
    "Commit": "131b7ed1f575446d67e1bfad6d60fe749d179f17"
  },
  "error": {
    "id": 2,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for GET: /db/svwsdb/reporting/ausgabe - Status: 500",
    "stack": [
      "Error: Fetch failed for GET: /db/svwsdb/reporting/ausgabe",
      "    at G0.postTextBasedToBinary (https://localhost:8443/assets/index.js:22:26811)",
      "    at async G0.pdfReport (https://localhost:8443/assets/index.js:53:658114)",
      "    at async https://localhost:8443/assets/index.js:56:423935",
      "    at async Proxy.<anonymous> (https://localhost:8443/assets/index.js:53:730871)",
      "    at async q (https://localhost:8443/assets/SGostKursplanung.js:1:104229)"
    ],
    "log": {
      "id": null,
      "success": false,
      "log": [
        ">>> Beginn des Initialisierens der Reporting-Factory und des Validierens übergebener Daten.",
        "    Erzeugung des Reporting-Repository",
        "    >>> Beginn der Erzeugung des Reporting-Repository",
        "        Ermittle Stammdaten und Abschnitte der Schule.",
        "        Ermittle Katalogdaten.",
        "        Ermittle die Lehrerstammdaten.",
        "        Ermittle die Jahrgangsdaten.",
        "        Ermittle die Klassendaten.",
        "        Ermittle Fächerdaten.",
        "        Ermittle alle Stundenplandefintionen der Schule.",
        "        Ermittle die Stundenpläne für den aktuellen und ausgewählten Schuljahresabschnitt.",
        "    <<< Ende der Erzeugung des Reporting-Repository",
        "<<< Ende des Initialisierens der Reporting-Factory und des Validierens übergebener Daten.",
        "### Beginn der Erzeugung einer API-Response zur Report-Generierung.",
        ">>> Beginn der Initialisierung der html-Factory und der Validierung der übergebenen Daten.",
        "    Prüfe die Berechtigungen des Benutzers für den Zugriff auf die für die Ausgabe notwendigen Daten.",
        "<<< Ende der Initialisierung der html-Factory und der Validierung der übergebenen Daten.",
        ">>> Beginn der Erzeugung der Datenkontexte für die html-Generierung.",
        "    Erzeuge Datenkontext Schule für die html-Generierung.",
        "    Validiere die Daten für ein Gost-Blockungsergebnis für die html-Generierung.",
        "    Erzeuge Datenkontext Gost-Kursplanung-Blockungsergebnis für die html-Generierung mit ID 63 für Template GOST_KURSPLANUNG_v_KURSE_MIT_STATISTIKWERTEN.",
        "### Fehler während der Erzeugung einer API-Response zur Report-Generierung. Fehlerdaten folgen.",
        "### Fehler",
        "    Pfad (key1=4902, key2=34) ungültig!"
      ]
    }
  }
}
```

**Comment by M-Plu** [comment]
Wie ist denn die Blockung der EF erzeugt worden? Aus der DB erzeugt, aus Kurs 42 importiert? Mit dem Client berechnet?

Der Fehler entsteht beim Aufbau der Datenstruktur außerhalb der Reporterzeugung. Da fehlt mir aber der Einblick. Ich leite das mal weiter.

**Comment by NielsWL** [comment]
Die Blockung wurde nach dem Import der Fachwahlen aus LuPO im Client berechnet.

**Comment by M-Plu** [comment]
Der Fehler lag nicht im Report, sondern in Schülern außerhalb des Abiturjahrgangs. Daher sollte auch der Ausdruck funktionieren. Wenn nicht Issue noch mal öffnen.
