### ISSUE TITLE
Oberstufe: Unzulässige Kombinationen löschen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#126]
Wenn ich unter Fächer unzulässige Kombinationen löschen möchte, erhalte ich die folgende Fehlermeldung.
Die DB ist frisch migriert.

{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT"
  },
  "error": {
    "id": 7,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for DELETE: /db/svwsdb/gost/fachkombination/15 - Status: 404",
    "stack": "Error: Fetch failed for DELETE: /db/svwsdb/gost/fachkombination/15\n    at ES.deleteTextBased (https://localhost:8443/assets/index.js:21:28327)\n    at async ES.deleteGostFachkombination (https://localhost:8443/assets/index.js:21:1029000)\n    at async Proxy.<anonymous> (https://localhost:8443/assets/index.js:41:336724)",
    "log": null
  }
}

**Comment by NielsWL** [comment]
Das Problem ist mit dem gerade aktualisierten Snapshot weg.
