### ISSUE TITLE
Kursplanung: Fehler beim Löschen einer Schiene

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#212]
```json
{
  "env": {
    "mode": "stable",
    "version": "0.9.0-SNAPSHOT",
    "Commit": "de7d41a202035b33d008b0b549aa9c49a0696337"
  },
  "error": {
    "id": 53,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "_mapSchienen.get(88) sollte nicht NULL sein!",
    "stack": [
      "es: _mapSchienen.get(88) sollte nicht NULL sein!",
      "    at es.ifNull (https://localhost:8443/assets/index.js:24:210791)",
      "    at Mi.schieneGet (https://localhost:8443/assets/index.js:26:36250)",
      "    at an.getSchieneG (https://localhost:8443/assets/index.js:47:54580)",
      "    at Tn (https://localhost:8443/assets/SGostKursplanung.js:1:65776)",
      "    at onClick (https://localhost:8443/assets/SGostKursplanung.js:1:77422)",
      "    at xu (https://localhost:8443/assets/index.js:14:38)",
      "    at Al (https://localhost:8443/assets/index.js:14:109)",
      "    at HTMLDivElement.e (https://localhost:8443/assets/index.js:18:8269)"
    ],
    "log": null
  }
}
```

**Comment by benjaminbartsch** [comment]
@NielsWL: Ich kann das nicht reproduzieren. Sobald es dir möglich ist, wäre es gut, wenn du uns eine Schritt für Schritt Anweisung erstellen könntest, wie man den Fehler triggert.

**Comment by benjaminbartsch** [comment]
Die Arbeitsweise des Blockungsergebnis-Managers wurde gerundlegend geändert. Infolgedessen ist der Fehler beim Löschen von Schienen nun nicht mehr vorhanden. Falls er dennoch reproduzierbar ist, dann bitte kurz beschreiben, wie man den Fehler erzeugen kann.
