### ISSUE TITLE
Fehlermeldung beim Stundenplanaufruf bei nicht sichtbaren Lehrkräften

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#264]
Ist eine Lehrkraft auf "Nicht sichtbar" gestellt, aber im Stundenplan mit drin wird eine Fehlermeldung generiert:

```
_lehrer_by_id hat nicht den KEY 133
An: _lehrer_by_id hat nicht den KEY 133
    at An.ifMapNotContains (https://localhost/assets/index.js:22:279672)
    at ft.kursCheckAttributes (https://localhost/assets/index.js:53:494288)
    at ft.kursAddAllOhneUpdate (https://localhost/assets/index.js:53:493577)
    at ft.initAll (https://localhost/assets/index.js:53:431454)
    at new ft (https://localhost/assets/index.js:53:430183)
    at tH.setEintrag (https://localhost/assets/index.js:56:195340)
    at async jx.update (https://localhost/assets/index.js:56:191779)
    at async jx.doUpdate (https://localhost/assets/index.js:56:60097)
    at async La.beforeEach (https://localhost/assets/index.js:59:9181)
```

![image](https://github.com/user-attachments/assets/f8d44d48-4f87-49c1-b27c-1f5050fcaddf)

**Comment by ThomasBachran** [comment]
Die Aggregation der Daten wurde angepasst, so dass nicht sichtbare Lehrer ggf. nachgeladen werden.

**Comment by AnneSchueller** [comment]
funktioniert jetzt
