### ISSUE TITLE
Kursplanung: Blocken scheitert

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#287]
Der Import der Blockungsergebnisse scheitert:

```json
{
  "env": {
    "mode": "stable",
    "version": "1.0.1-SNAPSHOT",
    "commit": "3705d3f195ae80b59c164b81b5eff52f2674dbe0"
  },
  "error": {
    "id": 1,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for POST: /db/svwsdb/gost/blockungen/5/addergebnisse - Status: 500",
    "stack": [
      "Error: Fetch failed for POST: /db/svwsdb/gost/blockungen/5/addergebnisse",
      "    at rI.postTextBased (https://localhost:8443/assets/index.js:22:289211)",
      "    at async rI.addGostBlockungErgebnisse (https://localhost:8443/assets/index.js:53:625069)",
      "    at async https://localhost:8443/assets/index.js:57:340182",
      "    at async Proxy.<anonymous> (https://localhost:8443/assets/index.js:56:54197)",
      "    at async D (https://localhost:8443/assets/SGostKursplanungAuswahl.js:1:13683)"
    ],
    "log": null
  }
}
```

![image](https://github.com/user-attachments/assets/3adf3d4b-caab-4a4e-98b0-fb5fd0da58e0)

Und wenn ich dann das Blocken abbreche und neu starte, kann ich beim nächsten Mal keine Ergebnisse übernehmen, da der Button ausgegraut ist.

![image](https://github.com/user-attachments/assets/93f90f21-349e-4dd2-8a03-beba805c5d24)

**Comment by NielsWL** [comment]
Das ist auch heute morgen reproduzierbar.

**Comment by hmt** [comment]
Sagen die Serverlogs etwas?

**Comment by ThomasBachran** [comment]
@NielsWL : Der Fehler ist im aktuellen dev-Branch behoben. Vielen Dank für die Rückmeldung.
