### ISSUE TITLE
Linux Installer "install-1.0.2.sh" |  Umgang mit Symbolic Links

### ISSUE THREAD

**Issue by betaprinz** [SVWS-NRW/SVWS-Server#323]
Hallo, 

ich will hier meine Beobachtungen schildern.

Meine Testinstallation ist etwas "exotisch".  "/etc" und "/opt" liegen auf separaten "Volumes / Platten"

Der `"install-1.0.2.sh"` erzeugt keine "Symbolic links" sondern "Hardlinks". 

```
# Erstelle einen symbolischen Link zur Konfigurationsdatei 
ln $CONF_PATH/svwsconfig.json $APP_PATH/svwsconfig.json
```

Hardlinks zwischen den Volumes sind nicht erlaubt, es kommt zu der Fehlermeldung

`ln: failed to create hard link '/opt/app/svws/svwsconfig.json' => '/etc/app/svws/conf/svwsconfig.json': Invalid cross-device link`

Mit echten symboliclinks kann die Software noch nicht umgehen / die Konfiguration (über echten symbolic link ) svwsconfig.json wird nicht gefunden.

```
Auszug aus JOURNALCTL #########################################

Dec 14 17:37:37 ubnt-schild-dummy systemd[1]: Started svws.service - SVWS Server.
Dec 14 17:37:38 ubnt-schild-dummy java[49872]: 2024-12-14T16:37:38.257 ERROR Konfiguration 'svwsconfig.json' nicht gefunden!
Dec 14 17:37:38 ubnt-schild-dummy java[49872]: 2024-12-14T16:37:38.261 ERROR Konfiguration 'svwsconfig.xml' nicht gefunden!
Dec 14 17:37:38 ubnt-schild-dummy java[49872]: 2024-12-14T16:37:38.261 INFO Erstelle leere Konfiguration mit Default-Werten...
Dec 14 17:37:38 ubnt-schild-dummy java[49872]: Exception in thread "main" java.lang.IllegalArgumentException: KeyStore Path not accessible: ./keystore
Dec 14 17:37:38 ubnt-schild-dummy java[49872]:         at org.eclipse.jetty.util.ssl.SslContextFactory.setKeyStorePath(SslContextFactory.java:655)
Dec 14 17:37:38 ubnt-schild-dummy java[49872]:         at de.svws_nrw.server.jetty.SvwsServer.getHttpServerConnector(SvwsServer.java:213)
Dec 14 17:37:38 ubnt-schild-dummy java[49872]:         at de.svws_nrw.server.jetty.SvwsServer.addHTTPServerConnections(SvwsServer.java:262)
Dec 14 17:37:38 ubnt-schild-dummy java[49872]:         at de.svws_nrw.server.jetty.SvwsServer.<init>(SvwsServer.java:106)
Dec 14 17:37:38 ubnt-schild-dummy java[49872]:         at de.svws_nrw.server.jetty.SvwsServer.instance(SvwsServer.java:120)
Dec 14 17:37:38 ubnt-schild-dummy java[49872]:         at de.svws_nrw.server.jetty.Main.main(Main.java:156)
Dec 14 17:37:38 ubnt-schild-dummy systemd[1]: svws.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 17:37:38 ubnt-schild-dummy systemd[1]: svws.service: Failed with result 'exit-code'.
```

Das Problem wird wohl nur eine kleine Anzahl der Admins betreffen.

**Comment by betaprinz** [comment]
Sorry, habe es an eine falsche Stelle "gesymlinked".

Habe gerade mit einer Kopie und einem richtigen symlink getestet.
Beides funktioniert.

Es sind 2 Stellen in der Bash

```
 # Erstelle einen symbolischen Link zur Konfigurationsdatei
 ln -f $CONF_PATH/svwsconfig.json $APP_PATH/svwsconfig.json
```

und

```
# Erstelle einen symbolischen Link zur Konfigurationsdatei
ln $CONF_PATH/svwsconfig.json $APP_PATH/svwsconfig.json
```


Offene Frage: Wird das ohne vorhandenne svwsconfig.json funktionieren?


```
# Überprüfe, ob eine leere Datenbank erstellt werden sollen
if [ "$INIT_EMPTY_DB" = "j" ] || [ "$INIT_EMPTY_DB" = "J" ]; then

	# Wechsle in das Verzeichnis der Anwendung
	cd $APP_PATH

	# Erstelle leere Datenbank ...
    echo "Erstelle leere Datenbank ..."
    java -cp "svws-server-app-*.jar:${APP_PATH}/app/*:${APP_PATH}/app/lib/*" de.svws_nrw.db.utils.app.CreateSchema -j -r -1 \
       -td "MARIA_DB" \
       -tl ${MariaDB_HOST} \
       -ts ${MariaDB_DATABASE} \
       -tu ${MariaDB_USER} \
       -tp ${MariaDB_PASSWORD} \
       -tr ${MariaDB_ROOT_PASSWORD}
fi
```

Ich werde mir morgen eine leere Datenbank basteln.

**Comment by hmt** [comment]
Gibt es einen guten Grund, warum wir harte Links nehmen?

**Comment by FPfotenhauer** [comment]
Ich werde morgen mal versuchen die symlinks einzubauen.

**Comment by betaprinz** [comment]
Habe heute bereits getestet. Der Installer lief durch

Einfach ein -s  oder --symbolic dranhängen .

```
# Erstelle einen symbolischen Link zur Konfigurationsdatei
ln -s $CONF_PATH/svwsconfig.json $APP_PATH/svwsconfig.json
```
und 

```
 # Erstelle einen symbolischen Link zur Konfigurationsdatei
 ln -f -s $CONF_PATH/svwsconfig.json $APP_PATH/svwsconfig.json
```

**Comment by FPfotenhauer** [comment]
Ist im nächsten Releqase drin.
