### ISSUE TITLE
Fehler bei Anzeige in Kurse

### ISSUE THREAD

**Issue by Gerritzma** [SVWS-NRW/SVWS-Server#6]
Wenn ein Kurs in der Tabelle Kurse im Feld Sortierung keinen Wert hat, liefert der Client diesen Fehler

Fetch failed for GET: /db/gg2/kurse/19706
Error: Fetch failed for GET: /db/gg2/kurse/19706
    at sy.getTextBased (https://localhost/assets/index.js:5:24812)
    at async sy.getKurs (https://localhost/assets/index.js:5:948467)
    at async Jh.setEintrag (https://localhost/assets/index.js:12:317865)
    at async CR.update (https://localhost/assets/index.js:12:320931)
    at async CR.doUpdate (https://localhost/assets/index.js:9:553404)
    at async Pr.beforeEach (https://localhost/assets/index.js:12:452109)

**Comment by ThomasBachran** [comment]
Dieser Fehler ist ab v0.7.1 behoben.
