### ISSUE TITLE
Kann keine Datenbank erstellen

### ISSUE THREAD

**Issue by frostieDE** [SVWS-NRW/SVWS-Server#9]
# Ausgangssituation

* Windows 11 x64
* JDK 17
* MariaDB 10.11.5 (läuft unter WSL2)
  * Root-Benutzer (Benutzername `root`) hat kein Passwort (wozu auch, ist ja eine Entwicklungsmaschine :))
  * Es gibt keine Datenbank `svws` (allerdings einen Haufen anderer Datenbanken)

Ich nutze folgende Konfigurationsdatei:

```json
{
  "EnableClientProtection" : null,
  "DisableDBRootAccess" : false,
  "DisableAutoUpdates" : false,
  "UseHTTPDefaultv11" : false,
  "PortHTTPS" : 8443,
  "UseCORSHeader" : true,
  "TempPath" : "tmp",
  "TLSKeyAlias" : null,
  "TLSKeystorePath" : ".",
  "TLSKeystorePassword" : "svwskeystore",
  "ClientPath" : "D:/Dev/SVWS/SVWS-Server/svws-webclient/build/output",
  "LoggingEnabled" : true,
  "LoggingPath" : "logs",
  "DBKonfiguration" : {
    "dbms" : "MARIA_DB",
    "location" : "localhost",
    "defaultschema" : "svws",
    "SchemaKonfiguration" : [ ]
  }
}
```

# Schritte zum Reproduzieren:
1. Ich starte den Server
2. Ich öffne den Browser und navigiere zu https://localhost:8443/debug
3. In der SwaggerUI wähle ich oben "Authorize" und trage als Benutzer `root` ein, das Passwortfeld bleibt leer. Anschließend klicke ich auf "Login"
4. Ich wähle den entsprechenden Endpunkt aus und versuche die `GymAbi.mdb` zu migrieren:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/3764924/08a993c3-587d-4248-adb4-0fbb57ed42ea)

Als Antwort erhalte ich:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/3764924/09a61d98-ff62-41aa-a845-ae3ff867c336)

In der Ausgabe vom Server erhalte ich:
```
Sept. 02, 2023 10:25:57 PM org.jboss.resteasy.core.ExceptionHandler handleWebApplicationException
ERROR: RESTEASY002010: Failed to execute
jakarta.ws.rs.WebApplicationException: HTTP 403 Forbidden
	at de.svws_nrw.db.utils.OperationError.exception(OperationError.java:100)
	at de.svws_nrw.api.OpenAPIApplication.getSVWSUser(OpenAPIApplication.java:225)
	at de.svws_nrw.api.OpenAPIApplication.getDBConnection(OpenAPIApplication.java:268)
	at de.svws_nrw.api.server.APIDatabase.migrateMDB(APIDatabase.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
RESTEASY002010: Failed to execute

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:222)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:538)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:122)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:451)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:125)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Ein kurzes Debuggen zeigt:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/3764924/225c4c62-931c-44ef-b578-3050b746ef63)

An dieser Stelle ist `user = null`.

# Erwartung
Die Migration sollte durchlaufen und ich habe am Ende eine aktuelle SVWS-Datenbank.

**Comment by frostieDE** [comment]
@M-Plu hat bemerkt, dass ich scheinbar den falschen Endpunkt genutzt habe. Das hier ist der richtige:

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/3764924/3e6c502b-e792-43d4-8505-561efe564f71)

Aber auch das scheitert bei mir:

```
[qtp365181913-20] WARN org.eclipse.jetty.server.HttpChannel - /api/schema/root/migrate/mdb/svws
Local Exception Stack: 
Exception [EclipseLink-30005] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa
Internal Exception: jakarta.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [SVWSDB] failed.
Internal Exception: Exception [EclipseLink-7351] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The converter class [de.svws_nrw.db.converter.current.BooleanPlusMinusDefaultPlusConverter] specified on the mapping attribute [Sichtbar] from the class [de.svws_nrw.db.dto.current.schild.schule.DTOAbteilungen] was not found. Please ensure the converter class name is correct and exists with the persistence unit definition.
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:129)
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:118)
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:191)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at de.svws_nrw.db.ConnectionManager.createEntityManagerFactory(ConnectionManager.java:151)
	at de.svws_nrw.db.ConnectionManager.<init>(ConnectionManager.java:56)
	at de.svws_nrw.db.ConnectionManager.get(ConnectionManager.java:174)
	at de.svws_nrw.db.Benutzer.<init>(Benutzer.java:59)
	at de.svws_nrw.db.Benutzer.create(Benutzer.java:72)
	at de.svws_nrw.api.OpenAPIPrincipal.login(OpenAPIPrincipal.java:133)
	at de.svws_nrw.server.jetty.SVWSLoginService.login(SVWSLoginService.java:76)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:61)
	at de.svws_nrw.server.jetty.SVWSAuthenticator.validateRequest(SVWSAuthenticator.java:69)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:508)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:122)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:451)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:125)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [SVWSDB] failed.
Internal Exception: Exception [EclipseLink-7351] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The converter class [de.svws_nrw.db.converter.current.BooleanPlusMinusDefaultPlusConverter] specified on the mapping attribute [Sichtbar] from the class [de.svws_nrw.db.dto.current.schild.schule.DTOAbteilungen] was not found. Please ensure the converter class name is correct and exists with the persistence unit definition.
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2150)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2126)
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:107)
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)
	... 37 more
Caused by: Exception [EclipseLink-28018] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [SVWSDB] failed.
Internal Exception: Exception [EclipseLink-7351] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The converter class [de.svws_nrw.db.converter.current.BooleanPlusMinusDefaultPlusConverter] specified on the mapping attribute [Sichtbar] from the class [de.svws_nrw.db.dto.current.schild.schule.DTOAbteilungen] was not found. Please ensure the converter class name is correct and exists with the persistence unit definition.
	at org.eclipse.persistence.exceptions.EntityManagerSetupException.predeployFailed(EntityManagerSetupException.java:233)
	... 41 more
Caused by: Exception [EclipseLink-7351] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The converter class [de.svws_nrw.db.converter.current.BooleanPlusMinusDefaultPlusConverter] specified on the mapping attribute [Sichtbar] from the class [de.svws_nrw.db.dto.current.schild.schule.DTOAbteilungen] was not found. Please ensure the converter class name is correct and exists with the persistence unit definition.
	at org.eclipse.persistence.exceptions.ValidationException.converterClassNotFound(ValidationException.java:2329)
	at org.eclipse.persistence.internal.jpa.metadata.converters.ConvertMetadata.apply(ConvertMetadata.java:292)
	at org.eclipse.persistence.internal.jpa.metadata.converters.ConvertMetadata.process(ConvertMetadata.java:353)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processConverts(MappingAccessor.java:1667)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingConverter(MappingAccessor.java:1872)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingValueConverter(MappingAccessor.java:1913)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.process(BasicAccessor.java:438)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataDescriptor.processMappingAccessors(MetadataDescriptor.java:1542)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processMappingAccessors(ClassAccessor.java:1659)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processMappingAccessors(EntityAccessor.java:1235)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.process(EntityAccessor.java:694)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage2(MetadataProject.java:1874)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:600)
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processORMetadata(PersistenceUnitProcessor.java:644)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2047)
	... 39 more
```

**Comment by FPfotenhauer** [comment]
Hast du den Server frisch gebaut?
Da ist einfach ein DTO nicht vorhanden, das sollte aber beim build erstellt werden.

**Comment by frostieDE** [comment]
> Hast du den Server frisch gebaut?

Ja. Mittels Git Clean alles gesäubert und dann Gradle Build ausgeführt. Anschließend den Server gestartet (nachdem ich die keystore und svwsconfig angelegt habe)

**Comment by frostieDE** [comment]
Nachtrag: ich habe gestern Abend ein `git pull` gemacht und bin auf c96488c26e948e105b284daee998a2ba6a6df4f3

**Comment by frostieDE** [comment]
Nachdem ich `grade rebuild` ausgeführt habe, klappt es nun 🤓

**Comment by frostieDE** [comment]
Da ich keinen Commit sehe, der eine Änderung für dieses Verhalten beinhaltet: Ist das Verhalten so (a) gewünscht oder kann (b) nicht reproduziert werden? Ist ja wichtig zu wissen, wenn man den Server bauen möchte :)
